# Generated by Django 6.0.2 on 2026-02-22 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=128, unique=True)),
                ('candidate_name', models.CharField(default='Candidate', max_length=128)),
                ('role', models.CharField(default='AI Algorithm Engineer Intern', max_length=256)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('ended', 'Ended'), ('error', 'Error')], default='created', max_length=32)),
                ('stage', models.CharField(choices=[('intro', 'Intro'), ('experience', 'Experience'), ('done', 'Done')], default='intro', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=16)),
                ('stage', models.CharField(default='intro', max_length=32)),
                ('text', models.TextField()),
                ('is_final', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interview.interviewsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'created_at'], name='interview_i_session_d87f8b_idx')],
            },
        ),
    ]
