# Generated by Django 6.0.2 on 2026-02-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='last_turn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='stage_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
